apiVersion: v1
kind: Service
metadata:
  name: nodetest
  labels:
    app: nodetest
spec:
  ports:
    - port: 3000
  selector:
    app: nodetest
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodetest
  labels:
    app: nodetest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodetest
  template:
    metadata:
      labels:
        app: nodetest
    spec:
      containers:
        - name: nodetest
          image: netscout82/nodetest:0.4
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m

